name: Build (with Buildozer master)
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages
  schedule:
      - cron: 0 0 */4 * * # at 00:00 UTC every fourth day

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android (with Buildozer master)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install OpenJDK
        run: sudo apt-get update && sudo apt-get install openjdk-8-jdk

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip tools.zip
          rm tools.zip
          echo "y" | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses

      - name: Set environment variables
        run: |
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\${PATH}:$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/tools/bin" >> $GITHUB_ENV

      - name: Build with Buildozer
        uses: ./master # REPLACE WITH ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          workdir: test_app
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: data
          ref: data # Branch name

      - name: Push binary to data branch
        if: github.event_name == 'push'
        run: python master/.ci/move_binary.py "${{ steps.buildozer.outputs.filename }}" master data bin-with-master
